### ISSUE TITLE
Omzetten bookdown Zoniën

### ISSUE THREAD

**Issue by RuttenAnneleen** [inbo/fis-projecten#11]
@Fhuysent : Kan je de map ~\opvolging-grofwild-domeinbossen\Sub_projects\Bookdown\Zonien omzetten naar de map 
~\fis-projecten\Grofwild\Zoniën en eventueel nodige pathways etc. aanpassen?

Hierna kunnen we de opvolging-grofwild-domeinbossen repo verwijderen

**Comment by jimcasaer** [comment]
@RuttenAnneleen @Fhuysent  waar zit die bookdown op dit moment ? ik zou die aan de waalse collega's moeten doorsturen voor nazicht
