### ISSUE TITLE
Aanvullen databank vangst-hervangst data everzwijnen

### ISSUE THREAD

**Issue by RuttenAnneleen** [inbo/fis-projecten#12]
Stappenplan om de databank aan te vullen: 

- [x] Anti-join tss Gemerkt GIS bestand en Teruggemeld GIS bestand --> (nog) niet teruggemelde individu's

- [x] Filter BackOffice Excel op zoek naar afgeschoten individu's met oormerk

- [x] Controleer nauwkeurigheid van coördinaten voor afgeschoten individu's met oormerk

- [ ] Nauwkeurige coördinaten toevoegen aan Teruggemeld GIS bestand

- [x] Onnauwkeurige coördinaten doorgeven aan @janvercammen 

- [ ] @janvercammen: Jagers opbellen voor nauwkeurige coördinaten

- [ ] Aangepaste coördinaten toevoegen aan Teruggemeld GIS bestand

- [ ] Nieuwe anti-join tss Gemerkt en Teruggemeld --> lijst van nog ongemelde individu's met oormerk

**Comment by RuttenAnneleen** [comment]
Voorbeeld directory:
aanzit_totaal <- read.csv('./Grofwild/Arendonk-Ravels/Data/Interim/jachtdagboekjes_aanzit_totaal.csv', 
                          header = TRUE, 
                          sep = ",")

**Comment by RuttenAnneleen** [comment]
Inlezen label_extracter:
source("../backoffice-wild-analyse/Functies/label_extracter.R")

Gebruik label_extracter:
#lijst maken van dataframe
labels <- data_2019_labels$labels

coord_2019 <- label_extracter(labels, presence=TRUE, columns = "group", choice = "coord")

**Comment by LynnINBO** [comment]
Ik heb gemerkt dat het stappenplan hierboven de eerste versie was, deze hieronder is de aangepaste

- [ ] Anti-join tss Gemerkt GIS bestand en Teruggemeld GIS bestand --> (nog) niet teruggemelde individu's

- [ ] BackOffice Excel handmatig op zoek naar afgeschoten individu's met oormerk

- [ ] Opslaan extra csv afgeschoten met oormerk

- [ ]  label_extractor op nieuw csv om coordinaten en nauwkeurigheid te krijgen

- [ ] Controleer nauwkeurigheid van coördinaten voor afgeschoten individu's met oormerk

- [ ] Nauwkeurige coördinaten toevoegen aan Teruggemeld GIS bestand

- [ ] Onnauwkeurige coördinaten doorgeven aan @janvercammen 

- [ ] @janvercammen: Jagers opbellen voor nauwkeurige coördinaten

- [ ] Aangepaste coördinaten toevoegen aan Teruggemeld GIS bestand

- [ ] Nieuwe anti-join tss Gemerkt en Teruggemeld --> lijst van nog ongemelde individu's met oormerk

**Comment by LynnINBO** [comment]
@RuttenAnneleen @janvercammen ik denk dat alle stappen om de lijst van onnauwkeurige coördinaten te bekomen, doorlopen zijn. we kunnen misschien morgen ergens mijn code doorlopen, om te zien of er geen massale fouten tussen staan? als dat niet het geval is, dan kan @janvercammen de lijst beginnen afgaan, en dan zal ik de nauwkeurige coördinaten aan het teruggemelde GIS toevoegen

**Comment by RuttenAnneleen** [comment]
@LynnINBO: is deze issue ondertussen niet afgewerkt?
Is hier al een pullrequest van geweest of is dit dezelfde branch als issue #15?

**Comment by LynnINBO** [comment]
Ja idd, hier is alles aangevuld geweest wat kon. Dit was branch 12-vangst-hervangst en dus die mag afgesloten worden.
Issue #15 (branch 15-populatiemodel) moet nog open blijven, daar wordt nog in gewerkt

**Comment by RuttenAnneleen** [comment]
Oke, top!
Ik sluit de issue af
