### ISSUE TITLE
Move scripts + data to new structure

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/fis-projecten#2]
#1

**Comment by RuttenAnneleen** [comment]
Branch 2-move to new structure aangemaakt

**Comment by RuttenAnneleen** [comment]
Update:

- Arendonk en Ravels + Meerdaal is verzet

- Tussentijdse pull request verstuurd om verder te kunnen met #4  en #5

**Comment by RuttenAnneleen** [comment]
Branch 2-move-scripts opnieuw aangemaakt

**Comment by RuttenAnneleen** [comment]
aanpassen pathways in grofwildprojecten:

- [ ] Arendonk-Ravels

- [ ] Basisscripts

- [ ] Everzwijn-Genetica

- [ ] Everzwijn-Survey

- [ ] Meerdaal

- [ ] Populatiemodel-Everzwijn

- [ ] Zoniën

**Comment by RuttenAnneleen** [comment]
Beslissing overleg Jim 29/09: map basisscripts in fis-projecten-grofwild repo zetten ipv apparte repo's voor basisscript jachtdagboekjes, populatietrends en KI

**Comment by RuttenAnneleen** [comment]
Status 28/10: Alle omzettingen en wiki's zijn aangemaakt behalve Everzwijn-survey
Wel al tussentijdse pull-request doen om up to date te zijn en makkelijk te kunnen verder werken aan projecten

**Comment by RuttenAnneleen** [comment]
Everzwijnensurvey map ook overgezet.
Deze issue is afgewerkt
